### PR TITLE
Alert user if their username or password is incorrect

### LINKED ISSUE #73: Alert User if the Login Data is incorrect

### PR DESCRIPTION
**Pull request by holladayian**
## Description
Clearly and concisely describe the feature.
This PR alerts a user if their login data is incorrect.

## Context
no

## Where To Start
It's literally only lines 237 & 238 of `index.js`

## Affected areas of application
List all parts of the website that will be altered from this PR.
The user is alerted if their username or password is incorrect.

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [X] Test A: Tested the DOM

## Relevant Tickets
Fixes #73 

## Tags
none

## Questions or Notes (if applicable):
please, no

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -234,6 +234,8 @@ function validateLogIn() {
         loginArea.classList.add('hidden');
         requestsButton.classList.remove('hidden');
         viewTrips.classList.remove('hidden');
+    } else {
+        alert("Your username or password is incorrect")
```
Comment (holladayian) [inline src/index.js:238]: Wow. I can tell that you put a lot of effort into this. I am very impressed with how clean this was. And so easy? Good job.

**Review by holladayian — COMMENTED** [review]
Git it

**Comment by holladayian** [comment]
I really learned a lot with this PR. The project might be unrecognizable without it...
